# Generated by Django 2.2 on 2019-05-17 08:40

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('categoria', django_mysql.models.EnumField(choices=[('Sismos', 'Sismos'), ('Caída de Ceniza', 'Caída de Ceniza'), ('Inundaciones', 'Inundaciones'), ('Asteroides y Cometas', 'Asteroides y Cometas'), ('Erupción Volcánica', 'Erupción Volcánica'), ('Inestabilidad de Laderas', 'Inestabilidad de Laderas')])),
                ('tipo', django_mysql.models.EnumField(choices=[('Proyectos', 'Proyectos'), ('Educación', 'Educación'), ('Reflexión', 'Reflexión'), ('Acción', 'Acción')])),
            ],
        ),
        migrations.CreateModel(
            name='Parrafo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitulo', models.CharField(blank=True, max_length=80, null=True)),
                ('parrafo', models.CharField(blank=True, max_length=800, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='video/')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('descripcionvideo', models.CharField(blank=True, max_length=200, null=True)),
                ('descripcionimagen', models.CharField(blank=True, max_length=200, null=True)),
                ('youtube', models.BooleanField(default=False)),
                ('esprincipal', models.BooleanField(default=False)),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entradas.Entrada')),
            ],
        ),
        migrations.CreateModel(
            name='Glosario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termino', models.CharField(max_length=30)),
                ('definicion', models.CharField(max_length=300)),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entradas.Entrada')),
            ],
        ),
    ]
